version: "3"
name: lab2
services:
    hazelcast-1:
        network_mode: 'hazelcast-network'
        container_name: 'lab21'
        environment:
            - 'HZ_NETWORK_PUBLICADDRESS=192.168.0.120:5701'
            - HZ_CLUSTERNAME=lab2
        ports:
            - '5701:5701'
        image: 'hazelcast/hazelcast:latest'
    hazelcast-2:
        network_mode: 'hazelcast-network'
        container_name: 'lab22'
        environment:
            - 'HZ_NETWORK_PUBLICADDRESS=192.168.0.120:5702'
            - HZ_CLUSTERNAME=lab2
        ports:
            - '5702:5701'
        image: 'hazelcast/hazelcast:latest'
    hazelcast-3:
        network_mode: 'hazelcast-network'
        container_name: 'lab23'
        environment:
            - 'HZ_NETWORK_PUBLICADDRESS=192.168.0.120:5703'
            - HZ_CLUSTERNAME=lab2
        ports:
            - '5703:5701'
        image: 'hazelcast/hazelcast:latest'
    hc-management:
      container_name: lab2-mc
      image: hazelcast/management-center:latest
      network_mode: hazelcast-network
      depends_on:
        - hazelcast-1
        - hazelcast-2
        - hazelcast-3
      ports:
        - 8080:8080
