version: "3"
services:
    hazelcast-1:
        network_mode: 'hazelcast-network'
        container_name: 'log-5701'
        environment:
            - 'HZ_NETWORK_PUBLICADDRESS=192.168.0.120:5701'
            - HZ_CLUSTERNAME=lab5
        ports:
            - '5701:5701'
        image: 'hazelcast/hazelcast:latest'