version: "3"
services:
    hazelcast-2:
        network_mode: 'hazelcast-network'
        container_name: 'log-5702'
        environment:
            - 'HZ_NETWORK_PUBLICADDRESS=192.168.0.120:5702'
            - HZ_CLUSTERNAME=lab3
        ports:
            - '5702:5701'
        image: 'hazelcast/hazelcast:latest'